import { describe, expect, it } from "vitest";
import { parseAdif, parseAdifDateTime } from "./adif";

const HEADER = "Generated by test\n<ADIF_VER:5>3.1.4\n<EOH>\n";

describe("parseAdifDateTime", () => {
	it("builds an ISO UTC timestamp from HHMM", () => {
		expect(parseAdifDateTime("20260601", "1200")).toBe(
			"2026-06-01T12:00:00.000Z"
		);
	});

	it("supports HHMMSS", () => {
		expect(parseAdifDateTime("20260601", "120030")).toBe(
			"2026-06-01T12:00:30.000Z"
		);
	});

	it("rejects malformed input", () => {
		expect(parseAdifDateTime("2026-06-01", "1200")).toBeNull();
	});
});

describe("parseAdif", () => {
	const record =
		"<CALL:5>LY3AB <BAND:3>20m <MODE:2>CW <QSO_DATE:8>20260601 <TIME_ON:4>1200 <MY_SIG:3>WAL <MY_SIG_INFO:3>A05 <SIG:3>WAL <SIG_INFO:3>B12 <EOR>";

	it("maps MY_SIG_INFO/SIG_INFO to squares and ignores MY_SIG/SIG", () => {
		const { qsos } = parseAdif(`${HEADER}${record}\n`);
		expect(qsos).toHaveLength(1);
		expect(qsos[0]).toMatchObject({
			contactCallsign: "LY3AB",
			band: "20m",
			mode: "CW",
			operatorSquare: "A05",
			contactSquare: "B12",
			qsoAt: "2026-06-01T12:00:00.000Z",
			issues: [],
		});
	});

	it("reads the station callsign from the header", () => {
		const { qsos, stationCallsign } = parseAdif(
			`Gen\n<STATION_CALLSIGN:5>LY2EN\n<EOH>\n${record}\n`
		);
		expect(stationCallsign).toBe("LY2EN");
		// Header station callsign is the per-record operator fallback.
		expect(qsos[0]?.operatorCallsign).toBe("LY2EN");
	});

	it("prefers a per-record STATION_CALLSIGN over the header", () => {
		const { qsos } = parseAdif(
			"Gen\n<STATION_CALLSIGN:5>LY2EN\n<EOH>\n<CALL:5>LY3AB <STATION_CALLSIGN:5>LY4CC <BAND:3>20m <MODE:2>CW <QSO_DATE:8>20260601 <TIME_ON:4>1200 <MY_SIG_INFO:3>A05 <EOR>\n"
		);
		expect(qsos[0]?.operatorCallsign).toBe("LY4CC");
	});

	it("derives band from FREQ when BAND is absent", () => {
		const { qsos } = parseAdif(
			`${HEADER}<CALL:5>LY3AB <FREQ:6>14.074 <MODE:3>FT8 <QSO_DATE:8>20260601 <TIME_ON:4>1200 <MY_SIG_INFO:3>A05 <EOR>\n`
		);
		expect(qsos[0]?.band).toBe("20m");
		expect(qsos[0]?.mode).toBe("DIGI");
	});

	it("maps SUBMODE when MODE does not resolve", () => {
		const { qsos } = parseAdif(
			`${HEADER}<CALL:5>LY3AB <BAND:3>20m <MODE:4>DATA <SUBMODE:3>FT8 <QSO_DATE:8>20260601 <TIME_ON:4>1200 <MY_SIG_INFO:3>A05 <EOR>\n`
		);
		expect(qsos[0]?.mode).toBe("DIGI");
	});

	it("keeps a missing operator square empty without a structural issue", () => {
		const { qsos } = parseAdif(
			`${HEADER}<CALL:5>LY3AB <BAND:3>20m <MODE:2>CW <QSO_DATE:8>20260601 <TIME_ON:4>1200 <EOR>\n`
		);
		expect(qsos[0]?.operatorSquare).toBe("");
		expect(qsos[0]?.issues).toEqual([]);
	});

	it("falls back to MY_GRIDSQUARE/GRIDSQUARE when SIG_INFO is absent", () => {
		const { qsos } = parseAdif(
			`${HEADER}<CALL:5>LY3AB <BAND:3>20m <MODE:2>CW <QSO_DATE:8>20260601 <TIME_ON:4>1200 <MY_GRIDSQUARE:6>KO24PR <GRIDSQUARE:6>KO24PR <EOR>\n`
		);
		expect(qsos[0]).toMatchObject({
			operatorSquare: "K26",
			contactSquare: "K26",
			issues: [],
		});
	});

	it("prefers explicit MY_SIG_INFO/SIG_INFO over the grid fallback", () => {
		const { qsos } = parseAdif(
			`${HEADER}<CALL:5>LY3AB <BAND:3>20m <MODE:2>CW <QSO_DATE:8>20260601 <TIME_ON:4>1200 <MY_SIG_INFO:3>A05 <MY_GRIDSQUARE:6>KO24PR <SIG_INFO:3>B12 <GRIDSQUARE:6>KO24PR <EOR>\n`
		);
		expect(qsos[0]?.operatorSquare).toBe("A05");
		expect(qsos[0]?.contactSquare).toBe("B12");
	});

	it("leaves the square empty when the grid locator is unmappable", () => {
		const { qsos } = parseAdif(
			`${HEADER}<CALL:5>LY3AB <BAND:3>20m <MODE:2>CW <QSO_DATE:8>20260601 <TIME_ON:4>1200 <MY_GRIDSQUARE:6>JJ00AA <EOR>\n`
		);
		expect(qsos[0]?.operatorSquare).toBe("");
	});

	it("parses multiple records", () => {
		const { qsos } = parseAdif(`${HEADER}${record}\n${record}\n`);
		expect(qsos).toHaveLength(2);
	});
});
