/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogRouteImport } from './routes/log'
import { Route as JoinSeasonRouteImport } from './routes/join-season'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSeasonsRouteImport } from './routes/admin.seasons'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSeasonRoute = JoinSeasonRouteImport.update({
  id: '/join-season',
  path: '/join-season',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeasonsRoute = AdminSeasonsRouteImport.update({
  id: '/admin/seasons',
  path: '/admin/seasons',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join-season': typeof JoinSeasonRoute
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/admin/seasons': typeof AdminSeasonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join-season': typeof JoinSeasonRoute
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/admin/seasons': typeof AdminSeasonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join-season': typeof JoinSeasonRoute
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/admin/seasons': typeof AdminSeasonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join-season'
    | '/log'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/upload'
    | '/admin/seasons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join-season'
    | '/log'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/upload'
    | '/admin/seasons'
  id:
    | '__root__'
    | '/'
    | '/join-season'
    | '/log'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/upload'
    | '/admin/seasons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinSeasonRoute: typeof JoinSeasonRoute
  LogRoute: typeof LogRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  UploadRoute: typeof UploadRoute
  AdminSeasonsRoute: typeof AdminSeasonsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-season': {
      id: '/join-season'
      path: '/join-season'
      fullPath: '/join-season'
      preLoaderRoute: typeof JoinSeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seasons': {
      id: '/admin/seasons'
      path: '/admin/seasons'
      fullPath: '/admin/seasons'
      preLoaderRoute: typeof AdminSeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinSeasonRoute: JoinSeasonRoute,
  LogRoute: LogRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  UploadRoute: UploadRoute,
  AdminSeasonsRoute: AdminSeasonsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
