/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as LogRouteImport } from './routes/log'
import { Route as JoinSeasonRouteImport } from './routes/join-season'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'
import { Route as AdminSeasonsRouteImport } from './routes/admin.seasons'
import { Route as AccountPathnameRouteImport } from './routes/account.$pathname'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSeasonRoute = JoinSeasonRouteImport.update({
  id: '/join-season',
  path: '/join-season',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeasonsRoute = AdminSeasonsRouteImport.update({
  id: '/admin/seasons',
  path: '/admin/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPathnameRoute = AccountPathnameRouteImport.update({
  id: '/account/$pathname',
  path: '/account/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join-season': typeof JoinSeasonRoute
  '/log': typeof LogRoute
  '/upload': typeof UploadRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join-season': typeof JoinSeasonRoute
  '/log': typeof LogRoute
  '/upload': typeof UploadRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join-season': typeof JoinSeasonRoute
  '/log': typeof LogRoute
  '/upload': typeof UploadRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join-season'
    | '/log'
    | '/upload'
    | '/verify-email'
    | '/account/$pathname'
    | '/admin/seasons'
    | '/auth/$pathname'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join-season'
    | '/log'
    | '/upload'
    | '/verify-email'
    | '/account/$pathname'
    | '/admin/seasons'
    | '/auth/$pathname'
  id:
    | '__root__'
    | '/'
    | '/join-season'
    | '/log'
    | '/upload'
    | '/verify-email'
    | '/account/$pathname'
    | '/admin/seasons'
    | '/auth/$pathname'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinSeasonRoute: typeof JoinSeasonRoute
  LogRoute: typeof LogRoute
  UploadRoute: typeof UploadRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AccountPathnameRoute: typeof AccountPathnameRoute
  AdminSeasonsRoute: typeof AdminSeasonsRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-season': {
      id: '/join-season'
      path: '/join-season'
      fullPath: '/join-season'
      preLoaderRoute: typeof JoinSeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seasons': {
      id: '/admin/seasons'
      path: '/admin/seasons'
      fullPath: '/admin/seasons'
      preLoaderRoute: typeof AdminSeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$pathname': {
      id: '/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof AccountPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinSeasonRoute: JoinSeasonRoute,
  LogRoute: LogRoute,
  UploadRoute: UploadRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AccountPathnameRoute: AccountPathnameRoute,
  AdminSeasonsRoute: AdminSeasonsRoute,
  AuthPathnameRoute: AuthPathnameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
